name: Go
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build_go:
    name: Run Go build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go install -race ./...
