name: Rebuild API when new Go release occurs
on:
  schedule:
    # Do this on the 47th minute of every hour.
    - cron: '47 */1 * * *'
  push:
    branches:
      - force_rebuild_api
      - master
jobs:
  make_rebuild_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1
      - run: ./rebuild.sh
      - run: echo "##[set-output name=pr_title;]rebuild API for new Go version $(cat docs/api/latest_version.txt)"
        id: pr_title_maker
      - name: Create pull request
        uses: peter-evans/create-pull-request@v1.5.2
        env:
          PULL_REQUEST_TITLE: ${{ steps.pr_title_maker.outputs.pr_title }}
          COMMIT_MESSAGE: ${{ steps.pr_title_maker.outputs.pr_title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_LABELS: autorebuild,autorebase
